### ISSUE TITLE
QUILTS Version3 Output Examples and Key and how to cont "the RNA splice junctions not in RefSeq"

### ISSUE THREAD

**Issue by pl618** [ekawaler/pyQUILTS#11]
Hi, Emily,

Thanks for your work on this software. I want to ask several questions about it:

1. Is this python version of QUILTS the same as the server version(http://openslice.fenyolab.org)  on core algorithm ?
2. Does this version 3 pyQUILTS have the output file keys to describe the results meaning?
3. Based on pyQUILTS, how to classify "RNA splice junctions not in RefSeq" to Partial exon/Complete exon/,frameshift/in-frame, which presented in Figure 1,b of this paper (https://www.nature.com/articles/nature18003) ?

Thanks a lot !

Peng Li

**Comment by ekawaler** [comment]
1. Yes
2. Not at the moment, though it's been requested
3. The output has been changed significantly since the paper was published. All junctions output by QUILTS are not in RefSeq. 
Junctions that skip one or more complete exons have a header that begins with: >NP_XXXX-bothJunc-chr1-96353-96320 (contains "bothJunc")
Junctions for which the donor site is at the end of an exon but the acceptor site is completely novel have a header that begins with: >NP_XXXX-donorJunc-chr1-94523-95923 (contains "donorJunc")
All other junctions are considered novel and have a header that begins with >NovelJunc

**Comment by pl618** [comment]
Thanks for your reply. I'm a newer in this filed and confusing on the definition of  "Partial exon/Complete exon/; frameshift/in-frame", would you like to explain  the definition of the 4 words? How to classify a junction is frameshift or in-frame ? Thanks.

**Comment by ekawaler** [comment]
You can read about it here https://en.wikipedia.org/wiki/Alternative_splicing
